/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gestortareas.interfacesGUI;

import gestortareas.DTO.TareaDetalle;

import java.sql.Timestamp;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author Michael
 */
public class DetalleTarea extends javax.swing.JDialog {
    private TareaDetalle tareaDetalle;
    /**
     * Creates new form DetalleTarea
     */
    public DetalleTarea(java.awt.Frame parent, boolean modal,TareaDetalle detalle) {
        super(parent, modal);
        this.tareaDetalle = detalle;
        initComponents();
        llenarCampos();
    }
    
    private void llenarCampos(){
        txtNombrePersona.setText(tareaDetalle.getNombresCompletos());
        txtNombreTarea.setText(tareaDetalle.getNombreTarea());
        jTextAreaDescripcion.setText(tareaDetalle.getDescripcion());
        fecha.setText(formaterDate(tareaDetalle.getFechaLimite()));
        jTextField1.setText(tareaDetalle.getCategoria());
        estad.setText(tareaDetalle.getEstado().toUpperCase());
        priori.setText(tareaDetalle.getPrioridad().toUpperCase());
        numFiles.setText(tareaDetalle.getNumeroArchivosAdjuntos() != 0? tareaDetalle.getNumeroArchivosAdjuntos() + " archivos adjuntos" : "0");
    }

    private String formaterDate(Date fecha){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        return formato.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        personaAsignada = new javax.swing.JLabel();
        nombreTarea = new javax.swing.JLabel();
        fechaLimite = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        prioridad = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        numArchivosAdjuntos = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        txtNombreTarea = new javax.swing.JTextField();
        jTextAreaDescripcion = new javax.swing.JTextArea();
        fecha = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        estad = new javax.swing.JTextField();
        priori = new javax.swing.JTextField();
        numFiles = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        title.setText("Detalle Tarea");

        personaAsignada.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        personaAsignada.setText("Nombre de la Persona Asignada:");

        nombreTarea.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        nombreTarea.setText("Titulo de la Tarea:");

        fechaLimite.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        fechaLimite.setText("Fecha Límite:");

        descripcion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        descripcion.setText("Descripción:");

        prioridad.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        prioridad.setText("Prioridad:");

        categoria.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        categoria.setText("Categoría:");

        estado.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        estado.setText("Estado:");

        numArchivosAdjuntos.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        numArchivosAdjuntos.setText("Archivos Adjuntos:");

        txtNombrePersona.setEditable(false);
        txtNombrePersona.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombrePersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtNombrePersona.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtNombreTarea.setEditable(false);
        txtNombreTarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        fecha.setEditable(false);
        fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jTextField1.setEditable(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        estad.setEditable(false);
        estad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        priori.setEditable(false);
        priori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        numFiles.setEditable(false);
        numFiles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personaAsignada)
                            .addComponent(nombreTarea)
                            .addComponent(descripcion)
                            .addComponent(fechaLimite)
                            .addComponent(estado)
                            .addComponent(prioridad)
                            .addComponent(numArchivosAdjuntos)
                            .addComponent(categoria))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priori, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(estad)
                                    .addComponent(jTextField1)
                                    .addComponent(txtNombreTarea)
                                    .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numFiles)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(title)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaAsignada)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTarea)
                    .addComponent(txtNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAreaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLimite))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priori, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prioridad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numArchivosAdjuntos))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel descripcion;
    private javax.swing.JTextField estad;
    private javax.swing.JLabel estado;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel fechaLimite;
    private javax.swing.JTextArea jTextAreaDescripcion;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombreTarea;
    private javax.swing.JLabel numArchivosAdjuntos;
    private javax.swing.JTextField numFiles;
    private javax.swing.JLabel personaAsignada;
    private javax.swing.JTextField priori;
    private javax.swing.JLabel prioridad;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNombreTarea;
    // End of variables declaration//GEN-END:variables
}
