package gestortareas.interfacesGUI;

import gestortareas.service.EmailService;
import gestortareas.service.UsuarioService;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael Medina
 */
public class frmIngresarCodigoClave extends javax.swing.JFrame {

    /**
     * Creates new form frmIngresarCodigoClave
     */
    private final EmailService emailService;
    private final UsuarioService usuarioService;
    private String correo;

    public frmIngresarCodigoClave(EmailService emailService, UsuarioService usuario, String correo) {
        this.emailService = emailService;
        this.usuarioService = usuario;
        this.correo = correo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        panelCodigo = new javax.swing.JPanel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        verContraseña = new javax.swing.JCheckBox();
        btnActualizar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabelCodigo.setText("Ingresar Código");

        jLabelContraseña.setText("Nueva Contraseña");

        verContraseña.setText("Ver contraseña");
        verContraseña.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                verContraseñaItemStateChanged(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCodigoLayout = new javax.swing.GroupLayout(panelCodigo);
        panelCodigo.setLayout(panelCodigoLayout);
        panelCodigoLayout.setHorizontalGroup(
            panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodigoLayout.createSequentialGroup()
                .addGroup(panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCodigoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContraseña)
                            .addComponent(jLabelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCodigoLayout.createSequentialGroup()
                                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(verContraseña))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCodigoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCodigoLayout.setVerticalGroup(
            panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodigoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContraseña)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verContraseña))
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nuevaContraseña = new String(contraseña.getPassword());
        if (txtCodigo.getText().trim().isEmpty() || nuevaContraseña.trim().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Ingrese el código de verificación y su nueva contraseña");

        } else {
            if (validarCodigo(txtCodigo.getText().trim())) {
                usuarioService.resetearPassoword(nuevaContraseña, correo);
                JOptionPane.showMessageDialog(rootPane, "Contraseña actualizada exitosamente");
            } else {
                JOptionPane.showMessageDialog(rootPane, "El código de verificación ingresado es incorrecto", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            }
        }
        java.util.Arrays.fill(contraseña.getPassword(), ' ');
    }//GEN-LAST:event_btnActualizarActionPerformed

    private boolean validarCodigo(String codigo) {
        return emailService.verificarCodigo(correo, codigo);
    }

    private void verContraseñaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_verContraseñaItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            contraseña.setEchoChar((char) 0);
        } else {
            contraseña.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_verContraseñaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIngresarCodigoClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIngresarCodigoClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIngresarCodigoClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIngresarCodigoClave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIngresarCodigoClave().setVisible(true);
            }
        });
         */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panelCodigo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JCheckBox verContraseña;
    // End of variables declaration//GEN-END:variables
}
